### ISSUE TITLE
JOSS Review 2

### ISSUE THREAD

**Issue by hsang** [erling6232/imagedata#6] opened 2022-04-15 13:24 UTC
Dear @erling6232,

my name is Hugo, and I am one of the reviewers assigned to your submission to JOSS. I found your contribution very easy to use and helpful. Congratulations!

These are my comments about your package and manuscript:

**installation**

- [ ]     As the other reviewer, I have some minor problems with the installation. In my case, imagedata was installed but when I ran a script, ModuleNotFoundErrors appeared. Easy to solve I guess.  Anyway, a clean environment works for me too.

**naming**

- [ ]     I agree with the other reviewer, it seems to me that "imagedata" is not specific enough.

**manuscript**

- [ ]   The manuscript is well written and easy to follow even for readers who are not familiar with the topic. The motivation seems clear. Just one minor issue, Figure 1 seems a bit blurred.

**package testing**

I checked the documentation and everything seems to work properly with the exception of the following issues:

- [ ] Be careful, some closing quotes are missing in "Saving data commands" section.   
- [ ] When I tried to save my data using itk format, an UnknownOptionType exception was raised.
- [ ] Adding DICOM template to Matlab formatted image showed an error: ` template_tag = template[_slice][tag][0] IndexError: list index out of range`

**documentation**

- [ ] In my opinion, it is not clear how to contribute to the software in the Community guidelines.

Please let me know if you have any questions regarding my comments. Thank you very much for your contribution.

Best regards,
Hugo

**Comment by erling6232** [comment] 2022-04-27 11:51
Dear Hugo (@hsang),

I am grateful for your thorough review! 

authors
-------
Added an additional author affiliation.

installation
------------
In order to examine your installation problem, it would be useful to have some details about your platform. You might
also want to submit a bug report.

naming
------
There are historic reasons for keeping the `imagedata` name, though I'm aware that a more specific name
could attract new users. Thinking of a new name, many of the good choices are already taken by (sometimes
abandonded) github projects. One particularly good name could have been `pydicom-series`. This name is,
however, used by some contribution to the pydicom package.

I will continue investigating the naming issue, also realizing that a name change will affect existing users.

manuscript
----------
Thank you for spotting the inferior Figure 1. A higher resolution figure has been uploaded now.

package testing
---------------
* Erroneous quotes in "Saving data commands" are corrected. Thanks! I would never have found those mistakes!
* UnknownOptionType in the write() method should only occur when the opts parameter is not dict-like. Can you share your script to reproduce?
* The IndexError exception should have been caught. Fixed in version 1.4.5. May I assume you got this exception due to different data shape in Matlab and DICOM?

documentation
-------------
An improved Community guideline has been uploaded in CONTRIBUTING.rst.

**Closed** 2022-10-24 08:23 UTC

**Comment by hsang** [comment] 2022-10-28 10:40
Sorry, @erling6232 , I can provide you some info about my installation issues.
